version: '3.3'

services:
    app:
        build: .
        container_name: app
        # entrypoint: dockerize -template .cd/.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        # environment:
        #     - DB_HOST=db
        #     - DB_DATABASE=laravel
        #     - DB_USERNAME=root
        #     - DB_PASSWORD=root
        volumes:
            - ./src:/var/www
        networks: 
            - app-network
        depends_on: 
            - db
            - redis
            
    nginx:
        build: .docker/nginx
        container_name: nginx
        # entrypoint: dockerize -template ./.docker/nginx/nginx.tmpl:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 -timeout 40s nginx
        environment:
            - APP_NAME=app
            - APP_PORT=9000
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www
        networks: 
            - app-network
        depends_on: 
            - app

    db: 
        build: .docker/mysql 
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
             - ./.docker/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - app-network


    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge